### ISSUE TITLE
App crashes when rotate device while displaying progress dialog

### ISSUE THREAD

**Issue by alabeduarte** [alabeduarte/mypodcasts-android#17]
```
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{1b5cb0c6 V.E..... R......D 0,0-684,232} not attached to window manager
    at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
    at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
    at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
    at android.app.Dialog.dismissDialog(Dialog.java:341)
    at android.app.Dialog.dismiss(Dialog.java:324)
    at com.mypodcasts.episodes.latestepisodes.LatestEpisodesActivity$LatestEpisodesAsyncTask.onPostExecute(LatestEpisodesActivity.java:64)
    at com.mypodcasts.episodes.latestepisodes.LatestEpisodesActivity$LatestEpisodesAsyncTask.onPostExecute(LatestEpisodesActivity.java:45)
    at retryable.asynctask.ConcreteAsyncTask.onPostExecute(ConcreteAsyncTask.java:34)
    at retryable.asynctask.ConcreteAsyncTask.onPostExecute(ConcreteAsyncTask.java:8)
    at android.os.AsyncTask.finish(AsyncTask.java:636)
    at android.os.AsyncTask.access$500(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5343)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by Pezhin** [comment]
Can you explain what is the cause for this bug?

I am developing and probably have encountered a same bug as this

**Comment by alabeduarte** [comment]
Hi @Pezhin 

I'm sorry for don't make this clear through the commits. Take a look on this post on stackoverflow, which summarises the issue: http://stackoverflow.com/a/23586127/3261242

Best

**Comment by Pezhin** [comment]
Thanks a lot
